version: "2"
services:
  echo-redis:
    expose:
      - "80"
      - "5000"
    networks:
      envoy-tcp-over-http:
        ipv4_address: 172.19.0.2
    restart: always
    environment:
      ECHO_PORT: 5000
      HTTP_PORT: 80
      REDIS_CLUSTER: "false"
      REDIS_HOST: 172.19.0.3:6969
      REDIS_RETRY: -1
      REDIS_IDLE_TIMEOUT: -1
    image: zufardhiyaulhaq/echo-redis:latest
  envoy-client:
    build: .
    expose:
      - "6969"
    networks:
      envoy-tcp-over-http:
        ipv4_address: 172.19.0.3
    restart: always
    volumes:
      - ./envoy-client.yaml:/etc/config.yaml
  envoy-server:
    build: .
    expose:
      - "80"
    networks:
      envoy-tcp-over-http:
        ipv4_address: 172.19.0.4
    restart: always
    volumes:
      - ./envoy-server.yaml:/etc/config.yaml
  redis:
    expose:
      - "6379"
    networks:
      envoy-tcp-over-http:
        ipv4_address: 172.19.0.5
    restart: always
    image: arm64v8/redis
networks:
  envoy-tcp-over-http:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1